name: Build APK

on:
  push:
    branches:
      - master  # or 'main' if your branch is named main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build APKs
        run: ./gradlew assembleDebug

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: aniyomi-extensions-apks
          path: "**/build/outputs/apk/debug/*.apk"
